all:
  hosts:
    cp1:
      ansible_host: 51.250.68.18
    node1:
      ansible_host: 51.250.71.171
    node2:
      ansible_host: 51.250.2.132
  vars:
    ansible_connection: ssh
    ansible_user: maxn
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
